version: 2.1

jobs:
  publish_to_dockerhub:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mvn clean install
      - setup_remote_docker
      - run: docker build -t kazzarin99/springboot_phonebook:latest application/.
      - run: docker build -t kazzarin99/springboot_phonebook_statistics:latest statistics/.
      - run: docker build -t kazzarin99/springboot_phonebook_notification:latest notification/.
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - run: docker image push kazzarin99/springboot_phonebook:latest
      - run: docker image push kazzarin99/springboot_phonebook_statistics:latest
      - run: docker image push kazzarin99/springboot_phonebook_notification:latest
  mvn_test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mvn test
workflows:
  build-then-publish:
    jobs:
      - mvn_test
      - publish_to_dockerhub:
          filters:
            branches:
              only:
                - master
