version: 2.1

jobs:
  publish_to_dockerhub:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Build maven project
          command: mvn clean install
      - setup_remote_docker
      - run:
          name: Build application image
          command: docker build -t kazzarin99/springboot_phonebook:latest application/.
      - run:
          name: Build user service image
          command: docker build -t kazzarin99/springboot_phonebook_user_service:latest userservice/.
      - run:
          name: Build statistics image
          command: docker build -t kazzarin99/springboot_phonebook_statistics:latest statistics/.
      - run:
          name: Build notification image
          command: docker build -t kazzarin99/springboot_phonebook_notification:latest notification/.
      - run:
          name: Login to docker hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - run:
          name: Push application image to docker hub
          command: docker image push kazzarin99/springboot_phonebook:latest
      - run:
          name: Push application image to docker hub
          command: docker image push kazzarin99/springboot_phonebook_user_service:latest
      - run:
          name: Push statistics image to docker hub
          command: docker image push kazzarin99/springboot_phonebook_statistics:latest
      - run:
          name: Push notification image to docker hub
          command: docker image push kazzarin99/springboot_phonebook_notification:latest
  mvn_test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Test application
          command: mvn test
workflows:
  build-then-publish:
    jobs:
      - mvn_test
      - publish_to_dockerhub:
          filters:
            branches:
              only:
                - master
