version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - attach_workspace:
          at: phonebook_temp
      - run: mvn clean install
      - persist_to_workspace:
          root: phonebook_temp
          paths:
            - application/target
            - application/Dockerfile
            - statistics/target
            - statistics/Dockerfile
            - notification/target
            - notification/Dockerfile
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: phonebook_temp
      - run: docker build -t kazzarin99/springboot_phonebook:latest phonebook_temp/application/.
      - run: docker build -t kazzarin99/springboot_phonebook_statistics:latest phonebook_temp/statistics/.
      - run: docker build -t kazzarin99/springboot_phonebook_notification:latest phonebook_temp/notification/.
      - run: docker image push kazzarin99/springboot_phonebook:latest
      - run: docker image push kazzarin99/springboot_phonebook_statistics:latest
      - run: docker image push kazzarin99/springboot_phonebook_notification:latest

workflows:
  build-then-publish:
    jobs:
      - build
      - publish
