version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mvn clean install
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: docker build -t kazzarin99/springboot_phonebook:latest application/.
      - run: docker build -t kazzarin99/springboot_phonebook_statistics:latest statistics/.
      - run: docker build -t kazzarin99/springboot_phonebook_notification:latest notification/.
      - run: docker image push kazzarin99/springboot_phonebook:latest
      - run: docker image push kazzarin99/springboot_phonebook_statistics:latest
      - run: docker image push kazzarin99/springboot_phonebook_notification:latest

workflows:
  build-then-publish:
    jobs:
      - build
      - publish
